apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-https-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # If you use cert-manager for automatic Let's Encrypt:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - my-spring-boot.example.com
      secretName: my-ssl-secret
  rules:
    - host: my-spring-boot.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-boot-https-service
                port:
                  number: 80